{
 "title": "Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{pod=~\"api-deployment-.*\", container=\"api\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Payments Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{container=\"payments\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Currency Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{container=\"currency\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{container=\"api\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))",
     "legendFormat": "API Pods"
    },
    {
     "expr": "count(prober_probe_total{container=\"payments\", result=\"successful\", probe_type=\"Liveness\"})",
     "legendFormat": "Payments Pods"
    },
    {
     "expr": "count(prober_probe_total{container=\"currency\", result=\"successful\", probe_type=\"Liveness\"})",
     "legendFormat": "Currency Pods"
    }
   ]
  },
  {
   "title": "API Downstream error count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(envoy_http_downstream_rq_xx{consul_source_service=\"ingress-gateway\", envoy_response_code_class=\"5\",envoy_http_conn_manager_prefix=\"ingress_upstream_18080\"}[$__rate_interval]),1))"
    }
   ]
  },
  {
   "title": "Payments Retries per Second",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(envoy_cluster_upstream_rq_retry{consul_destination_service=\"payments\"}[$__rate_interval]),1))"
    }
   ]
  },
  {
   "title": "Currency Retries per Second",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(envoy_cluster_upstream_rq_retry{consul_destination_service=\"currency\"}[$__rate_interval]),1))"
    }
   ]
  },
  {
   "title": "Payments Outlier Ejection",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{consul_destination_service=\"payments\"})"
    }
   ]
  },
  {
   "title": "API Request Per Second",
   "type": "timeseries",
   "description": "Note: Mention that envoy has multiple clusters all of which independently report stats. We should build a flow diagram that shows the flow of data through envoy and all the metrics that it touches.",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_listener_http_downstream_rq_xx{consul_source_service=\"api\", envoy_http_conn_manager_prefix=\"public_listener\"}[$__rate_interval])) by (envoy_response_code_class) != 0",
     "legendFormat": "Downstream Response Code {{envoy_response_code_class}}xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{consul_source_service=\"api\", consul_destination_service=\"payments\"}[$__rate_interval])) by (envoy_response_code) != 0",
     "legendFormat": "Upstream Payments Response Code {{envoy_response_code}}"
    },
    {
     "expr": "rate(envoy_cluster_retry_upstream_rq_xx{consul_source_service=\"api\", consul_destination_service=\"payments\"}[$__rate_interval])",
     "legendFormat": "Upstream Payments Retry Failures {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Payments Request Per Second",
   "type": "timeseries",
   "description": "Note: Mention that envoy has multiple clusters all of which independently report stats. We should build a flow diagram that shows the flow of data through envoy and all the metrics that it touches.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{consul_source_service=\"payments\"}[$__rate_interval])) by (envoy_response_code_class) != 0",
     "legendFormat": "Downstream Response Code {{envoy_response_code_class}}xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_source_service=\"payments\", local_cluster=\"payments\"}[$__rate_interval])) by (envoy_response_code_class) != 0",
     "legendFormat": "Upstream Response Code {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "API Request Per Second",
   "type": "timeseries",
   "description": "Note: Mention that envoy has multiple clusters all of which independently report stats. We should build a flow diagram that shows the flow of data through envoy and all the metrics that it touches.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{consul_source_service=\"api\", consul_upstream_service=\"payments\"}[$__rate_interval])) by (envoy_response_code_class) != 0",
     "legendFormat": "Downstream Response Code {{envoy_response_code_class}}xx"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{consul_source_service=\"api\"}[$__rate_interval])",
     "legendFormat": "Upstream Response Code {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Latency - API",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Latency - Payments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"payments\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"payments\"}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"payments\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "{app=\"api\"}"
    }
   ]
  },
  {
   "title": "Payments Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "{app=~\"payments.*\"}"
    }
   ]
  }
 ]
}